[
  { name: "Hamilton, Bermuda", index: "136.83" },
  { name: "Zurich, Switzerland", index: "129.11" },
  { name: "Basel, Switzerland", index: "127.71" },
  { name: "Geneva, Switzerland", index: "120.70" },
  { name: "Lausanne, Switzerland", index: "120.10" },
  { name: "Bern, Switzerland", index: "119.45" },
  { name: "Reykjavik, Iceland", index: "113.22" },
  { name: "Lugano, Switzerland", index: "113.08" },
  { name: "Stavanger, Norway", index: "111.53" },
  { name: "Oslo, Norway", index: "108.99" },
  { name: "Bergen, Norway", index: "103.76" },
  { name: "Trondheim, Norway", index: "100.24" },
  { name: "New York, NY, United States", index: "100.00" },
  { name: "San Francisco, CA, United States", index: "96.05" },
  { name: "Nassau, Bahamas", index: "95.92" },
  { name: "Honolulu, HI, United States", index: "94.66" },
  { name: "Anchorage, AK, United States", index: "93.06" },
  { name: "Brooklyn, NY, United States", index: "89.21" },
  { name: "Santa Rosa, CA, United States", index: "87.90" },
  { name: "Singapore, Singapore", index: "87.83" },
  { name: "Washington, DC, United States", index: "87.60" },
  { name: "Tokyo, Japan", index: "87.58" },
  { name: "Copenhagen, Denmark", index: "87.37" },
  { name: "Luxembourg, Luxembourg", index: "87.02" },
  { name: "Rockville, MD, United States", index: "86.80" },
  { name: "Charleston, SC, United States", index: "86.59" },
  { name: "Seoul, South Korea", index: "86.01" },
  { name: "Bellevue, WA, United States", index: "85.82" },
  { name: "Paris, France", index: "85.63" },
  { name: "Seattle, WA, United States", index: "84.94" },
  { name: "Odense, Denmark", index: "84.78" },
  { name: "Aalborg, Denmark", index: "83.47" },
  { name: "Amsterdam, Netherlands", index: "83.25" },
  { name: "London, United Kingdom", index: "82.38" },
  { name: "Sydney, Australia", index: "82.03" },
  { name: "Arhus, Denmark", index: "81.99" },
  { name: "Berkeley, CA, United States", index: "81.79" },
  { name: "Jersey City, NJ, United States", index: "81.63" },
  { name: "Boston, MA, United States", index: "81.44" },
  { name: "Hartford, CT, United States", index: "81.28" },
  { name: "Oakland, CA, United States", index: "81.06" },
  { name: "Dublin, Ireland", index: "80.84" },
  { name: "Helsinki, Finland", index: "80.54" },
  { name: "Tel Aviv-Yafo, Israel", index: "80.32" },
  { name: "Philadelphia, PA, United States", index: "79.74" },
  { name: "Auckland, New Zealand", index: "79.46" },
  { name: "Jerusalem, Israel", index: "79.41" },
  { name: "Grenoble, France", index: "79.19" },
  { name: "Milton Keynes, United Kingdom", index: "79.14" },
  { name: "Linz, Austria", index: "79.02" },
  { name: "Lyon, France", index: "78.70" },
  { name: "Boulder, CO, United States", index: "78.60" },
  { name: "Irvine, CA, United States", index: "78.36" },
  { name: "Los Angeles, CA, United States", index: "78.12" },
  { name: "Stockholm, Sweden", index: "78.03" },
  { name: "Barrie, Canada", index: "77.99" },
  { name: "Nice, France", index: "77.84" },
  { name: "Perth, Australia", index: "77.71" },
  { name: "Reading, United Kingdom", index: "77.20" },
  { name: "Florence, Italy", index: "77.11" },
  { name: "Toulouse, France", index: "77.09" },
  { name: "Pittsburgh, PA, United States", index: "77.00" },
  { name: "Miami, FL, United States", index: "76.99" },
  { name: "Albany, NY, United States", index: "76.91" },
  { name: "Strasbourg, France", index: "76.86" },
  { name: "Tampere, Finland", index: "76.72" },
  { name: "Brussels, Belgium", index: "76.68" },
  { name: "Leuven, Belgium", index: "76.60" },
  { name: "Bordeaux, France", index: "76.48" },
  { name: "Chicago, IL, United States", index: "76.40" },
  { name: "The Hague (Den Haag), Netherlands", index: "76.34" },
  { name: "Melbourne, Australia", index: "76.32" },
  { name: "Graz, Austria", index: "76.22" },
  { name: "Utrecht, Netherlands", index: "76.19" },
  { name: "Haifa, Israel", index: "76.18" },
  { name: "Genoa, Italy", index: "76.07" },
  { name: "Burlington, VT, United States", index: "76.04" },
  { name: "Osaka, Japan", index: "76.02" },
  { name: "Antwerp, Belgium", index: "76.01" },
  { name: "Hamilton, New Zealand", index: "75.86" },
  { name: "Sacramento, CA, United States", index: "75.79" },
  { name: "San Jose, CA, United States", index: "75.68" },
  { name: "Long Beach, CA, United States", index: "75.41" },
  { name: "Bath, United Kingdom", index: "75.40" },
  { name: "Milan, Italy", index: "75.32" },
  { name: "Adelaide, Australia", index: "75.31" },
  { name: "Maastricht, Netherlands", index: "75.26" },
  { name: "Portland, OR, United States", index: "75.10" },
  { name: "Gent, Belgium", index: "75.08" },
  { name: "Innsbruck, Austria", index: "75.07" },
  { name: "Burlington, Canada", index: "75.03" },
  { name: "Hong Kong, Hong Kong", index: "74.97" },
  { name: "West Palm Beach, FL, United States", index: "74.90" },
  { name: "Tacoma, WA, United States", index: "74.69" },
  { name: "Cambridge, United Kingdom", index: "74.65" },
  { name: "Santa Barbara, CA, United States", index: "74.64" },
  { name: "Ramat Gan, Israel", index: "74.60" },
  { name: "Saskatoon, Canada", index: "74.51" },
  { name: "Espoo, Finland", index: "74.45" },
  { name: "Munich, Germany", index: "74.43" },
  { name: "Darwin, Australia", index: "74.41" },
  { name: "Saint Paul, MN, United States", index: "74.29" },
  { name: "Olympia, WA, United States", index: "74.23" },
  { name: "Baltimore, MD, United States", index: "74.21" },
  { name: "Aberdeen, United Kingdom", index: "74.14" },
  { name: "Galway, Ireland", index: "74.13" },
  { name: "Charlotte, NC, United States", index: "74.10" },
  { name: "St. John's, NL, Canada", index: "74.07" },
  { name: "New Orleans, LA, United States", index: "74.04" },
  { name: "Eugene, OR, United States", index: "73.97" },
  { name: "Wellington, New Zealand", index: "73.89" },
  { name: "Oxford, United Kingdom", index: "73.88" },
  { name: "Cork, Ireland", index: "73.86" },
  { name: "Minneapolis, MN, United States", index: "73.76" },
  { name: "Newcastle, Australia", index: "73.34" },
  { name: "Christchurch, New Zealand", index: "73.32" },
  { name: "Dunedin, New Zealand", index: "73.26" },
  { name: "Hobart, Australia", index: "72.96" },
  { name: "Rotterdam, Netherlands", index: "72.95" },
  { name: "Denver, CO, United States", index: "72.84" },
  { name: "San Diego, CA, United States", index: "72.80" },
  { name: "Brisbane, Australia", index: "72.79" },
  { name: "Birmingham, AL, United States", index: "72.68" },
  { name: "Halifax, Canada", index: "72.67" },
  { name: "Padova, Italy", index: "72.51" },
  { name: "Hamburg, Germany", index: "72.48" },
  { name: "Gothenburg, Sweden", index: "72.45" },
  { name: "Eindhoven, Netherlands", index: "72.28" },
  { name: "Bellingham, WA, United States", index: "72.28" },
  { name: "Sliema, Malta", index: "72.26" },
  { name: "Atlanta, GA, United States", index: "72.26" },
  { name: "Edinburgh, United Kingdom", index: "72.24" },
  { name: "Asheville, NC, United States", index: "72.02" },
  { name: "Nantes, France", index: "72.00" },
  { name: "Dusseldorf, Germany", index: "71.75" },
  { name: "Tampa, FL, United States", index: "71.72" },
  { name: "Groningen, Netherlands", index: "71.68" },
  { name: "Vienna, Austria", index: "71.54" },
  { name: "Manchester, United Kingdom", index: "71.54" },
  { name: "Canberra, Australia", index: "71.51" },
  { name: "Trieste, Italy", index: "71.49" },
  { name: "Frankfurt, Germany", index: "71.38" },
  { name: "Indianapolis, IN, United States", index: "71.37" },
  { name: "Buffalo, NY, United States", index: "71.34" },
  { name: "Toronto, Canada", index: "71.13" },
  { name: "Jacksonville, FL, United States", index: "71.12" },
  { name: "Austin, TX, United States", index: "71.05" },
  { name: "Vancouver, Canada", index: "70.98" },
  { name: "Limerick, Ireland", index: "70.82" },
  { name: "Orlando, FL, United States", index: "70.73" },
  { name: "Brighton, United Kingdom", index: "70.70" },
  { name: "Rochester, NY, United States", index: "70.66" },
  { name: "Turku, Finland", index: "70.49" },
  { name: "Brampton, Canada", index: "70.48" },
  { name: "Fayetteville, AR, United States", index: "70.37" },
  { name: "Plymouth, United Kingdom", index: "70.25" },
  { name: "Bristol, United Kingdom", index: "70.22" },
  { name: "Colorado Springs, CO, United States", index: "70.22" },
  { name: "Saint Petersburg, FL, United States", index: "70.13" },
  { name: "York, United Kingdom", index: "69.84" },
  { name: "Bologna, Italy", index: "69.72" },
  { name: "Thunder Bay, Canada", index: "69.64" },
  { name: "Calgary, Canada", index: "69.58" },
  { name: "Leeds, United Kingdom", index: "69.35" },
  { name: "Regina, Canada", index: "69.35" },
  { name: "Rome, Italy", index: "69.29" },
  { name: "Milwaukee, WI, United States", index: "69.14" },
  { name: "Heidelberg, Germany", index: "69.04" },
  { name: "Coquitlam, Canada", index: "69.01" },
  { name: "Saint Louis, MO, United States", index: "69.00" },
  { name: "Peoria, IL, United States", index: "68.91" },
  { name: "Dubai, United Arab Emirates", index: "68.85" },
  { name: "Karlsruhe, Germany", index: "68.70" },
  { name: "Nottingham, United Kingdom", index: "68.62" },
  { name: "Lille, France", index: "68.58" },
  { name: "Cleveland, OH, United States", index: "68.55" },
  { name: "Raleigh, NC, United States", index: "68.48" },
  { name: "Kelowna, Canada", index: "68.40" },
  { name: "Nashville, TN, United States", index: "68.32" },
  { name: "Virginia Beach, VA, United States", index: "68.32" },
  { name: "Edmonton, Canada", index: "68.24" },
  { name: "Ann Arbor, MI, United States", index: "68.11" },
  { name: "Uppsala, Sweden", index: "68.09" },
  { name: "Syracuse, NY, United States", index: "67.91" },
  { name: "Melbourne, FL, United States", index: "67.89" },
  { name: "Malmo, Sweden", index: "67.86" },
  { name: "Taipei, Taiwan", index: "67.85" },
  { name: "Red Deer, Canada", index: "67.81" },
  { name: "Fort Myers, FL, United States", index: "67.73" },
  { name: "Berlin, Germany", index: "67.67" },
  { name: "Coventry, United Kingdom", index: "67.63" },
  { name: "Las Vegas, NV, United States", index: "67.62" },
  { name: "Kingston, Canada", index: "67.56" },
  { name: "Exeter, United Kingdom", index: "67.54" },
  { name: "Bremen, Germany", index: "67.25" },
  { name: "Gold Coast, Australia", index: "67.19" },
  { name: "Guelph, Canada", index: "67.17" },
  { name: "Victoria, Canada", index: "67.09" },
  { name: "Bonn, Germany", index: "67.00" },
  { name: "Columbus, OH, United States", index: "67.00" },
  { name: "Bakersfield, CA, United States", index: "66.95" },
  { name: "Fort Wayne, IN, United States", index: "66.94" },
  { name: "Oshawa, Canada", index: "66.85" },
  { name: "Columbia, SC, United States", index: "66.76" },
  { name: "Memphis, TN, United States", index: "66.76" },
  { name: "Nanaimo, BC, Canada", index: "66.69" },
  { name: "Salem, OR, United States", index: "66.68" },
  { name: "Cologne, Germany", index: "66.62" },
  { name: "Glasgow, United Kingdom", index: "66.59" },
  { name: "Aachen, Germany", index: "66.57" },
  { name: "Stuttgart, Germany", index: "66.57" },
  { name: "Turin, Italy", index: "66.55" },
  { name: "Spokane, WA, United States", index: "66.52" },
  { name: "Windsor, Canada", index: "66.48" },
  { name: "Mississauga, Canada", index: "66.45" },
  { name: "Kansas City, MO, United States", index: "66.25" },
  { name: "San Juan, Puerto Rico", index: "66.17" },
  { name: "Leicester, United Kingdom", index: "66.17" },
  { name: "Palma De Mallorca, Spain", index: "66.10" },
  { name: "Fresno, CA, United States", index: "65.99" },
  { name: "Norwich, United Kingdom", index: "65.99" },
  { name: "Greensboro, NC, United States", index: "65.83" },
  { name: "Fort Worth, TX, United States", index: "65.62" },
  { name: "Richmond, VA, United States", index: "65.61" },
  { name: "Burnaby, Canada", index: "65.60" },
  { name: "Naples, Italy", index: "65.45" },
  { name: "Dayton, OH, United States", index: "65.23" },
  { name: "Montreal, Canada", index: "65.05" },
  { name: "Newcastle Upon Tyne, United Kingdom", index: "65.05" },
  { name: "Southampton, United Kingdom", index: "64.96" },
  { name: "Quebec City, Canada", index: "64.87" },
  { name: "Gainesville, FL, United States", index: "64.87" },
  { name: "Wichita, KS, United States", index: "64.75" },
  { name: "Nuremberg, Germany", index: "64.67" },
  { name: "Phoenix, AZ, United States", index: "64.50" },
  { name: "Winnipeg, Canada", index: "64.48" },
  { name: "Leipzig, Germany", index: "64.43" },
  { name: "Winston-salem, NC, United States", index: "64.43" },
  { name: "Kingston, Jamaica", index: "64.37" },
  { name: "Birmingham, United Kingdom", index: "64.34" },
  { name: "Dresden, Germany", index: "64.33" },
  { name: "Albuquerque, NM, United States", index: "64.23" },
  { name: "Dallas, TX, United States", index: "64.18" },
  { name: "Ottawa, Canada", index: "64.11" },
  { name: "Taichung, Taiwan", index: "64.09" },
  { name: "Derby, United Kingdom", index: "64.00" },
  { name: "Hanover, Germany", index: "63.85" },
  { name: "Belfast, United Kingdom", index: "63.67" },
  { name: "Madison, WI, United States", index: "63.62" },
  { name: "Chattanooga, TN, United States", index: "63.52" },
  { name: "Liverpool, United Kingdom", index: "63.43" },
  { name: "Tucson, AZ, United States", index: "63.42" },
  { name: "Tulsa, OK, United States", index: "63.38" },
  { name: "Marseille, France", index: "63.35" },
  { name: "Salt Lake City, UT, United States", index: "63.17" },
  { name: "Grand Rapids, MI, United States", index: "63.16" },
  { name: "Cagliari, Italy", index: "63.11" },
  { name: "Cincinnati, OH, United States", index: "63.05" },
  { name: "Barcelona, Spain", index: "63.05" },
  { name: "Detroit, MI, United States", index: "62.96" },
  { name: "Doha, Qatar", index: "62.88" },
  { name: "Sheffield, United Kingdom", index: "62.77" },
  { name: "Houston, TX, United States", index: "62.76" },
  { name: "Des Moines, IA, United States", index: "62.75" },
  { name: "Cardiff, United Kingdom", index: "62.72" },
  { name: "Moncton, Canada", index: "62.58" },
  { name: "Lubbock, TX, United States", index: "62.49" },
  { name: "Abu Dhabi, United Arab Emirates", index: "62.28" },
  { name: "Sioux Falls, SD, United States", index: "62.14" },
  { name: "London, Canada", index: "62.04" },
  { name: "Springfield, MO, United States", index: "61.84" },
  { name: "Hamilton, Canada", index: "61.72" },
  { name: "Beirut, Lebanon", index: "61.54" },
  { name: "Palermo, Italy", index: "61.51" },
  { name: "Louisville, KY, United States", index: "61.46" },
  { name: "Vancouver, WA, United States", index: "61.28" },
  { name: "Little Rock, AR, United States", index: "61.27" },
  { name: "Oklahoma City, OK, United States", index: "61.23" },
  { name: "Nicosia, Cyprus", index: "61.10" },
  { name: "Surrey, Canada", index: "60.90" },
  { name: "Madrid, Spain", index: "60.53" },
  { name: "Knoxville, TN, United States", index: "60.42" },
  { name: "Toledo, OH, United States", index: "60.32" },
  { name: "Reno, NV, United States", index: "60.30" },
  { name: "Athens, Greece", index: "60.23" },
  { name: "Huntsville, AL, United States", index: "60.12" },
  { name: "Kitchener, Canada", index: "60.09" },
  { name: "Abbotsford, Canada", index: "59.86" },
  { name: "Lexington, KY, United States", index: "59.85" },
  { name: "Malta, Malta", index: "59.76" },
  { name: "Boise, ID, United States", index: "59.76" },
  { name: "Port Of Spain, Trinidad And Tobago", index: "59.63" },
  { name: "Montevideo, Uruguay", index: "59.26" },
  { name: "San Antonio, TX, United States", index: "58.71" },
  { name: "Zaragoza (Saragossa), Spain", index: "58.54" },
  { name: "Kaohsiung, Taiwan", index: "57.98" },
  { name: "Thessaloniki, Greece", index: "57.84" },
  { name: "Limassol, Cyprus", index: "57.79" },
  { name: "San Jose, Costa Rica", index: "57.77" },
  { name: "El Paso, TX, United States", index: "57.59" },
  { name: "Mobile, AL, United States", index: "57.32" },
  { name: "Ljubljana, Slovenia", index: "56.72" },
  { name: "Accra, Ghana", index: "56.46" },
  { name: "Manama, Bahrain", index: "55.80" },
  { name: "Valencia, Spain", index: "55.73" },
  { name: "Amman, Jordan", index: "55.32" },
  { name: "Sevilla, Spain", index: "55.17" },
  { name: "Panama City, Panama", index: "55.17" },
  { name: "Sharjah, United Arab Emirates", index: "55.09" },
  { name: "Tallinn, Estonia", index: "54.94" },
  { name: "Larnaca, Cyprus", index: "54.91" },
  { name: "Lisbon, Portugal", index: "54.62" },
  { name: "Split, Croatia", index: "53.95" },
  { name: "Rijeka, Croatia", index: "53.27" },
  { name: "Shanghai, China", index: "53.15" },
  { name: "Bangkok, Thailand", index: "53.00" },
  { name: "Zagreb, Croatia", index: "52.59" },
  { name: "Makati, Philippines", index: "52.35" },
  { name: "Santiago, Chile", index: "52.03" },
  { name: "Funchal, Portugal", index: "51.55" },
  { name: "Muscat, Oman", index: "51.45" },
  { name: "Al Khobar, Saudi Arabia", index: "51.36" },
  { name: "Riga, Latvia", index: "51.23" },
  { name: "Coimbra, Portugal", index: "51.13" },
  { name: "Jeddah (Jiddah), Saudi Arabia", index: "50.60" },
  { name: "Malaga, Spain", index: "50.59" },
  { name: "Porto, Portugal", index: "50.54" },
  { name: "Pretoria, South Africa", index: "50.44" },
  { name: "Granada, Spain", index: "50.43" },
  { name: "Tartu, Estonia", index: "50.26" },
  { name: "Havana, Cuba", index: "50.21" },
  { name: "Windhoek, Namibia", index: "50.04" },
  { name: "Vilnius, Lithuania", index: "49.40" },
  { name: "Phuket, Thailand", index: "49.29" },
  { name: "Addis Ababa, Ethiopia", index: "49.29" },
  { name: "Maribor, Slovenia", index: "49.20" },
  { name: "Bratislava, Slovakia", index: "49.04" },
  { name: "Harare, Zimbabwe", index: "49.03" },
  { name: "Braga, Portugal", index: "48.89" },
  { name: "Prague, Czech Republic", index: "48.72" },
  { name: "Johannesburg, South Africa", index: "48.65" },
  { name: "Santa Cruz De Tenerife, Spain", index: "48.48" },
  { name: "Quito, Ecuador", index: "48.24" },
  { name: "Riyadh, Saudi Arabia", index: "48.07" },
  { name: "Ad Dammam, Saudi Arabia", index: "47.94" },
  { name: "San Salvador, El Salvador", index: "47.92" },
  { name: "Las Palmas, Spain", index: "47.76" },
  { name: "Guayaquil, Ecuador", index: "47.42" },
  { name: "Klaipeda, Lithuania", index: "47.32" },
  { name: "Campinas, Brazil", index: "46.76" },
  { name: "Kaunas, Lithuania", index: "46.68" },
  { name: "Phnom Penh, Cambodia", index: "46.36" },
  { name: "Kosice, Slovakia", index: "46.11" },
  { name: "Beijing, China", index: "46.11" },
  { name: "Rio De Janeiro, Brazil", index: "46.08" },
  { name: "Johor Bahru, Malaysia", index: "46.06" },
  { name: "Baghdad, Iraq", index: "45.92" },
  { name: "Sao Paulo, Brazil", index: "45.83" },
  { name: "Cape Town, South Africa", index: "45.71" },
  { name: "Brasilia, Brazil", index: "45.56" },
  { name: "Selangor, Malaysia", index: "45.45" },
  { name: "Budapest, Hungary", index: "45.36" },
  { name: "Santo Domingo, Dominican Republic", index: "45.35" },
  { name: "Brno, Czech Republic", index: "45.35" },
  { name: "Petaling Jaya, Malaysia", index: "45.30" },
  { name: "Osijek, Croatia", index: "45.20" },
  { name: "Moscow, Russia", index: "45.19" },
  { name: "Penang, Malaysia", index: "45.17" },
  { name: "Buenos Aires, Argentina", index: "44.42" },
  { name: "Shenzhen, China", index: "44.29" },
  { name: "Guatemala City, Guatemala", index: "44.17" },
  { name: "Kuala Lumpur, Malaysia", index: "43.78" },
  { name: "Gdansk, Poland", index: "43.71" },
  { name: "Pattaya, Thailand", index: "43.56" },
  { name: "Warsaw, Poland", index: "43.45" },
  { name: "Durban, South Africa", index: "43.44" },
  { name: "Kota Kinabalu, Malaysia", index: "43.15" },
  { name: "Kuching, Malaysia", index: "43.02" },
  { name: "Fortaleza, Brazil", index: "42.94" },
  { name: "Bali, Indonesia", index: "42.86" },
  { name: "Irbil, Iraq", index: "42.86" },
  { name: "Porto Alegre, Brazil", index: "42.86" },
  { name: "Jakarta, Indonesia", index: "42.85" },
  { name: "Recife, Brazil", index: "42.83" },
  { name: "Port Elizabeth, South Africa", index: "42.82" },
  { name: "Gdynia, Poland", index: "42.23" },
  { name: "Guangzhou, China", index: "42.21" },
  { name: "Olomouc, Czech Republic", index: "42.07" },
  { name: "Nairobi, Kenya", index: "41.88" },
  { name: "Florianopolis, Brazil", index: "41.73" },
  { name: "Belo Horizonte, Brazil", index: "41.72" },
  { name: "Chiang Mai, Thailand", index: "41.63" },
  { name: "Salvador, Brazil", index: "41.48" },
  { name: "Wroclaw, Poland", index: "41.24" },
  { name: "Lima, Peru", index: "41.14" },
  { name: "Ostrava, Czech Republic", index: "41.13" },
  { name: "Krakow (Cracow), Poland", index: "41.00" },
  { name: "Bucharest, Romania", index: "40.69" },
  { name: "Natal, Brazil", index: "40.52" },
  { name: "Sofia, Bulgaria", index: "40.35" },
  { name: "Sao Jose dos Campos, Brazil", index: "40.34" },
  { name: "Podgorica, Montenegro", index: "40.20" },
  { name: "Belgrade, Serbia", index: "40.15" },
  { name: "Saint Petersburg, Russia", index: "40.14" },
  { name: "Curitiba, Brazil", index: "39.79" },
  { name: "Poznan, Poland", index: "39.77" },
  { name: "Suzhou, China", index: "39.72" },
  { name: "Szeged, Hungary", index: "39.70" },
  { name: "Bydgoszcz, Poland", index: "39.64" },
  { name: "Sarajevo, Bosnia And Herzegovina", index: "39.57" },
  { name: "Varna, Bulgaria", index: "39.02" },
  { name: "Debrecen, Hungary", index: "38.80" },
  { name: "Hanoi, Vietnam", index: "38.78" },
  { name: "Manila, Philippines", index: "38.73" },
  { name: "Ho Chi Minh City, Vietnam", index: "38.55" },
  { name: "Rabat, Morocco", index: "38.53" },
  { name: "Szczecin, Poland", index: "38.38" },
  { name: "Timisoara, Romania", index: "38.15" },
  { name: "Cluj-Napoca, Romania", index: "38.10" },
  { name: "Katowice, Poland", index: "38.07" },
  { name: "Lodz, Poland", index: "38.06" },
  { name: "Tirana, Albania", index: "37.83" },
  { name: "Chelyabinsk, Russia", index: "37.82" },
  { name: "Constanta, Romania", index: "37.54" },
  { name: "Chengdu, China", index: "37.50" },
  { name: "Cebu, Philippines", index: "37.27" },
  { name: "Yekaterinburg, Russia", index: "37.17" },
  { name: "Istanbul, Turkey", index: "37.11" },
  { name: "Banja Luka, Bosnia And Herzegovina", index: "36.86" },
  { name: "Lublin, Poland", index: "36.84" },
  { name: "Plovdiv, Bulgaria", index: "36.71" },
  { name: "Samara, Russia", index: "36.70" },
  { name: "Surabaya, Indonesia", index: "36.70" },
  { name: "Iasi, Romania", index: "36.60" },
  { name: "Burgas, Bulgaria", index: "36.57" },
  { name: "Cuenca, Ecuador", index: "36.52" },
  { name: "Brasov, Romania", index: "36.45" },
  { name: "Bandung, Indonesia", index: "36.44" },
  { name: "Kaliningrad, Russia", index: "36.44" },
  { name: "Colombo, Sri Lanka", index: "36.19" },
  { name: "Sibiu, Romania", index: "36.07" },
  { name: "Yogyakarta, Indonesia", index: "35.98" },
  { name: "Astana, Kazakhstan", index: "35.98" },
  { name: "Bogota, Colombia", index: "35.62" },
  { name: "Novi Sad, Serbia", index: "35.59" },
  { name: "Casablanca, Morocco", index: "35.56" },
  { name: "Skopje, Macedonia", index: "35.18" },
  { name: "Barranquilla, Colombia", index: "34.79" },
  { name: "Ulaanbaatar, Mongolia", index: "34.66" },
  { name: "Monterrey, Mexico", index: "34.63" },
  { name: "Lagos, Nigeria", index: "34.62" },
  { name: "Nis, Serbia", index: "34.40" },
  { name: "Nizhny Novgorod, Russia", index: "34.33" },
  { name: "Kazan, Russia", index: "34.30" },
  { name: "Algiers, Algeria", index: "34.18" },
  { name: "Medellin, Colombia", index: "34.14" },
  { name: "Novosibirsk, Russia", index: "34.12" },
  { name: "Minsk, Belarus", index: "34.01" },
  { name: "Oradea, Romania", index: "33.91" },
  { name: "Dumaguete, Philippines", index: "33.90" },
  { name: "Bursa, Turkey", index: "33.88" },
  { name: "Ankara, Turkey", index: "33.69" },
  { name: "Chisinau, Moldova", index: "33.69" },
  { name: "Mexico City, Mexico", index: "33.55" },
  { name: "Almaty, Kazakhstan", index: "33.53" },
  { name: "Yerevan, Armenia", index: "33.38" },
  { name: "Izmir, Turkey", index: "33.31" },
  { name: "Asuncion, Paraguay", index: "33.30" },
  { name: "Kathmandu, Nepal", index: "32.93" },
  { name: "Krasnodar, Russia", index: "32.92" },
  { name: "Rostov-na-donu, Russia", index: "32.92" },
  { name: "Voronezh, Russia", index: "32.34" },
  { name: "Quezon City, Philippines", index: "32.31" },
  { name: "Craiova, Romania", index: "32.03" },
  { name: "Kampala, Uganda", index: "32.02" },
  { name: "Tijuana, Mexico", index: "32.00" },
  { name: "Tehran, Iran", index: "31.99" },
  { name: "Davao, Philippines", index: "31.83" },
  { name: "Guadalajara, Mexico", index: "31.76" },
  { name: "Cancun, Mexico", index: "31.34" },
  { name: "Gurgaon, India", index: "31.26" },
  { name: "Cali, Colombia", index: "31.14" },
  { name: "Queretaro, Mexico", index: "31.06" },
  { name: "Dhaka, Bangladesh", index: "30.99" },
  { name: "Tashkent, Uzbekistan", index: "30.78" },
  { name: "Odesa, Ukraine", index: "30.43" },
  { name: "Antalya, Turkey", index: "30.27" },
  { name: "Eskisehir, Turkey", index: "29.90" },
  { name: "Sheridan, WY, United States", index: "29.83" },
  { name: "Merida, Mexico", index: "29.72" },
  { name: "Mumbai, India", index: "29.65" },
  { name: "Baku, Azerbaijan", index: "29.58" },
  { name: "Kiev, Ukraine", index: "29.55" },
  { name: "Tbilisi, Georgia", index: "29.48" },
  { name: "Delhi, India", index: "29.43" },
  { name: "Puebla, Mexico", index: "29.33" },
  { name: "Puerto Vallarta, Mexico", index: "28.99" },
  { name: "Caracas, Venezuela", index: "28.80" },
  { name: "Noida, India", index: "28.75" },
  { name: "Pune, India", index: "27.95" },
  { name: "Dnipropetrovsk, Ukraine", index: "27.94" },
  { name: "Bangalore, India", index: "27.38" },
  { name: "Lviv, Ukraine", index: "27.33" },
  { name: "Lahore, Pakistan", index: "27.28" },
  { name: "Islamabad, Pakistan", index: "27.15" },
  { name: "Chandigarh, India", index: "26.89" },
  { name: "Tunis, Tunisia", index: "26.69" },
  { name: "Kharkiv, Ukraine", index: "26.63" },
  { name: "Pristina, Kosovo (Disputed Territory)", index: "26.35" },
  { name: "Jaipur, India", index: "26.30" },
  { name: "Isfahan (Esfahan), Iran", index: "26.12" },
  { name: "Khartoum, Sudan", index: "25.85" },
  { name: "Thane, India", index: "25.75" },
  { name: "Cairo, Egypt", index: "25.71" },
  { name: "Mashhad, Iran", index: "25.62" },
  { name: "Kolkata, India", index: "25.58" },
  { name: "Chennai, India", index: "25.53" },
  { name: "Lucknow (Lakhnau), India", index: "25.41" },
  { name: "Indore, India", index: "25.35" },
  { name: "Karachi, Pakistan", index: "25.04" },
  { name: "Goa, India", index: "24.94" },
  { name: "Ahmedabad, India", index: "24.52" },
  { name: "Surat, India", index: "24.36" },
  { name: "Hyderabad, India", index: "24.13" },
  { name: "Sumy, Ukraine", index: "24.01" },
  { name: "Alexandria, Egypt", index: "23.82" },
  { name: "Guwahati, India", index: "23.25" },
  { name: "Nagpur, India", index: "23.23" },
  { name: "Bhopal, India", index: "23.09" },
  { name: "Vadodara, India", index: "23.05" },
  { name: "Mangalore, India", index: "22.95" },
  { name: "Bhubaneswar, India", index: "22.87" },
  { name: "Coimbatore, India", index: "22.73" },
  { name: "Mysore, India", index: "22.57" },
  { name: "Kochi, India", index: "22.52" },
  { name: "Visakhapatnam, India", index: "22.06" },
  { name: "Navi Mumbai, India", index: "19.94" },
  { name: "Thiruvananthapuram, India", index: "19.17" }
];
